### ISSUE TITLE
Patch 3.6.4 to fix multi-thread compression crasher

### ISSUE THREAD

**Issue by sgillies** [sgillies/rasterio-wheels#107]
See https://github.com/rasterio/rasterio/issues/2847. Fix is in https://github.com/OSGeo/gdal/pull/7963.

**Comment by rouault** [comment]
you should actually backport https://github.com/OSGeo/gdal/pull/7967 , since the master PR will not apply on 3.7 or 3.6

you may also want to cherry-pick https://github.com/OSGeo/gdal/pull/7962 that will avoid annoying (harmless) error messages in the same situation

**Comment by sgillies** [comment]
Yes, thanks @rouault !

**Comment by sgillies** [comment]
Resolved by #110
