### ISSUE TITLE
Build and upload Python 3.12 wheels

### ISSUE THREAD

**Issue by EwoutH** [sgillies/rasterio-wheels#111]
Python 3.12 releases in [exactly a week](https://peps.python.org/pep-0693/)! It would be awesome if Rasterio has wheels up by then.

**Comment by sgillies** [comment]
@EwoutH I agree. In #110 I've been working on it. It's slow for several reasons. I've been overcoming small changes to the free tier CI runner images that we're using, and I'm unemployed, looking for my next job. Historically, I get paid to build wheels as a small part of my day job. My employers and their customers have been major users of rasterio. Distributing binaries is a kinda big job on top of the job of maintaining the code. Doing it for free is, in my opinion, not sustainable or healthy. I'm not ready or willing to make a business of distributing binaries, so, for now, I'm asking for patience.

**Comment by sgillies** [comment]
Resolved by #110.

**Comment by EwoutH** [comment]
@sgillies Thanks a lot for building these wheels, especially in your own time.

Would some sort of funding/support make maintaining these project viable? From the top of my head, the [Open Source Geospatial Foundation](https://www.osgeo.org/), [NumFOCUS](https://numfocus.org/) and/or the [Chan Zuckerberg Initiative](https://chanzuckerberg.com/) are currently funding scientific Python projects.

**Comment by sgillies** [comment]
@EwoutH Yes, I thinking funding would help enable the project to hire someone, part time, to maintain wheel building infrastructure. And to pay for running it. But then applying for funding, hiring someone, and making sure that money is spent responsibly becomes a bit of a job in itself, one that I've been avoiding by doing this myself over the years. It's all about the tradeoffs, as in any endeavor, right?
