### ISSUE TITLE
Add nghttp2 to enable http/2 in CURL 

### ISSUE THREAD

**Issue by vincentsarago** [sgillies/rasterio-wheels#13]
👋 Hi @sgillies, 
Adding HTTP/2 to rasterio wheels could be really useful. I'll open a PR later and we can discuss if this is a good idea :-)

**Comment by sgillies** [comment]
I'm willing to give it a try. I think I've mostly solved the build issues here, but now Travis-CI is jammed. Maybe we'll get this merged tomorrow.

**Comment by vincentsarago** [comment]
thanks @sgillies. 
before shipping this I'd love to make sure it resolve this kind of problem https://github.com/RemotePixel/amazonlinux-gdal/issues/7 where GDAL is not working with the CURL libraries I expected on AWS Lambda. I'm pretty sure working with wheels will resolve it (I hope)
