### ISSUE TITLE
switch to libwebp 1.0.1 

### ISSUE THREAD

**Issue by vincentsarago** [sgillies/rasterio-wheels#20]
Ran a quick benchmark over https://github.com/vincentsarago/benchmark-img-gdal and it seems that libwebp 1.0.1 is a bit faster than the one use un rasterio wheels (1.0.0) 

Happy to submit a PR 😄

**Comment by sgillies** [comment]
@vincentsarago 1.0.3 and 1.1.0 are out now. I think I'll update this project to use 1.0.3. I'd love to see some reports that 1.1.0 will work, I don't have time to look into it right now.

**Comment by vincentsarago** [comment]
👌 I'm stuck at 1.0.2, but I'll try to test 1.1.0
