### ISSUE TITLE
Build libjpeg with libjpeg turbo 

### ISSUE THREAD

**Issue by vincentsarago** [sgillies/rasterio-wheels#21]
as for #20, without libjpegturbo (shipped within wheels) libjpeg seems to be slower (in comparison to the one built with libjpegturbo). Might be a nice thing to consider adding.

That's said I need to mention that user are raising question about rasterio wheels being to heavy ref: https://github.com/mojodna/marblecutter-virtual/issues/8, adding another lib might make some people unhappy!

**Comment by sgillies** [comment]
:-1: on another library.
