### ISSUE TITLE
Add ZSTD compression

### ISSUE THREAD

**Issue by sgillies** [sgillies/rasterio-wheels#23]
Requires libzstd and probably GDAL configuration flags.

**Comment by vincentsarago** [comment]
I was going to open an issue about this :D, I'll try to open a PR.

**Comment by snowman2** [comment]
Looks like it is included in libtiff 4.0.10: http://libtiff.maptools.org/v4.0.10.html

**Comment by sgillies** [comment]
I wish I'd written down *why* to add ZSTD support. I never see such files at work and I don't see this as a "must have" for the wheels.

**Comment by sgillies** [comment]
@snowman2 thanks for pointing that out. GDAL doesn't include libzstd though, so we would still need to add fetching and building the lib to https://github.com/rasterio/rasterio-wheels/blob/master/config.sh (or whatever we do in the future).
