### ISSUE TITLE
GDAL 3.1 and PROJ 7.1

### ISSUE THREAD

**Issue by sgillies** [sgillies/rasterio-wheels#53]
It's not that I haven't wanted to, it's that changes in PROJ 6 and 7 have impacted packaging and environment configuration. But it's time to do this.

PROJ doesn't need data files any more; it can fetch data from the PROJ CDN. I think this will be the default for new wheels.

**Comment by vincentsarago** [comment]
I'm kinda hesitant to the switch, we always avoided the switch to GDAL 3.1 because we found it was a bit slower than version 2.4 
Not saying it's a bad thing but maybe we could wait for version 1.2 to switch the GDAL version in the wheels?

**Comment by sgillies** [comment]
Slower depending on sqlite version, right? The wheels will include sqlite, so I'd be sure to upgrade it. Except for OS X, where we use the system one.

**Comment by sgillies** [comment]
We've got 3.24 in the manylinux1 wheels now, which meets the requirements of 3.11 mentioned in https://github.com/OSGeo/PROJ/issues/1718.

**Comment by sgillies** [comment]
@vincentsarago I promise I'll mail the rasterio discussion group about this tomorrow.

**Comment by sgillies** [comment]
From https://rasterio.groups.io/g/main/topic/76829482#605 I conclude.

* Reports of latency are anecdotal.
* We're better of waiting for PROJ 7.2 to skip PROKJ data (see https://github.com/pyproj4/pyproj/issues/689)

**Comment by sgillies** [comment]
Done!
