### ISSUE TITLE
Out of Travis credits

### ISSUE THREAD

**Issue by sgillies** [sgillies/rasterio-wheels#64]
The rasterio org's free plan is out of credits. I'll ask Travis support for OSS only credits. Meanwhile, I've created a private copy of this repo in my employer's org and will build on that plan (paid by Mapbox).

**Comment by vincentsarago** [comment]
is moving to GitHub actions an option?

**Comment by sgillies** [comment]
@vincentsarago maybe. The build is rather complicated and there would be a lot to move and then painstakingly debug. Would you rather have me fixing rasterio bugs or have me fiddling with a new build system, that's the question :smile:  In the longer term, after 1.2.0 is done, I'm going to try to catch back up with the practices of pillow-wheels, numpy-wheels, &c. It looks like they are moving more builds to GHA and AppVeyor.

**Comment by vincentsarago** [comment]
> Would you rather have me fixing rasterio bugs or have me fiddling with a new build system, that's the question 

I'd rather have you filling my strava logs ;-) 

> 'm going to try to catch back up with the practices of pillow-wheels, numpy-wheels, &c. It looks like they are moving more builds to GHA and AppVeyor.

👍 

I guess my question, was more, if moving to GHA is something possible, maybe I could have a look or just let @kylebarron do the job ;-)

**Comment by sgillies** [comment]
Status update: still building wheels from the fork at mapbox/rasterio-wheels, pushing changes here. There's a big update coming soon. Moving to manylinux2014 unlocked upgrades to the latest versions of almost everything.
