### ISSUE TITLE
add libdeflate for faster TIFF decompression

### ISSUE THREAD

**Issue by vincentsarago** [sgillies/rasterio-wheels#66]
because we are using libtiff internal with gdal3.2 I think it will be good to add libdeflate: https://github.com/OSGeo/gdal/pull/3068

**Comment by sgillies** [comment]
@vincentsarago libdeflate isn't building on macos or with manylinux1 (CentOS 5 based). This will have to wait for the future.

![](https://media.giphy.com/media/RJKHjCAdsAfQPn03qQ/giphy.gif)

**Comment by snowman2** [comment]
`manylinux2010`?
