### ISSUE TITLE
Add support for LERC compression

### ISSUE THREAD

**Issue by maawoo** [sgillies/rasterio-wheels#70]
My knowledge about the internals of GDAL and rasterio is probably barely scratching the surface, so excuse my ignorance, but is it possible to include support for LERC compression in the near future? 
Coming from [here](https://github.com/mapbox/rasterio/issues/2270) with a bit more background info. 

Regards, Marco

**Comment by sgillies** [comment]
@maawoo I took a look at the LERC v3.0 release today and found its build system and instructions inadequate. For example, the library version in the Makefile is incorrect. For now, I won't include it in the rasterio wheels.

cc @vincentsarago

**Comment by maawoo** [comment]
Hello @sgillies,
I was just informed in https://github.com/Esri/lerc/issues/173 that some work has been done in response to your comment. Maybe you can take another look at some time.

Regards, Marco
