### ISSUE TITLE
HDF5 cross-compilation issues block macosx arm64 wheels

### ISSUE THREAD

**Issue by sgillies** [sgillies/rasterio-wheels#75]
HDF5's configure needs to run some system tests, but when cross compiling the test programs can't be run on the build host. It looks like the conda-forge project has a solution in https://github.com/conda-forge/hdf5-feedstock/pull/145/files. We need much of this, but not all (no fortran or MPI needed), if we want to make macosx arm64 wheels with HDF5/netcdf drivers on an ordinary GitHub Actions x86_64 runner.

Kicking HDF5/netcdf out of these wheel profiles is another option.

**Comment by snowman2** [comment]
Is this still possible in Travis? If so, maybe run OSX builds in Travis until a workaround is found?

**Comment by sgillies** [comment]
It's an option. Not a free one, though.

**Comment by dg0yt** [comment]
FTR it *is* possible to cross-build hdf5 if someone could provide the output of the test programs from a native build. (And I think it could be integrated in the vcpkg port...)

**Comment by snowman2** [comment]
Cirrus CI has ARM64 runners: https://github.com/pyproj4/pyproj/pull/1173

**Comment by sgillies** [comment]
Checking out Cirrus today.

**Comment by sgillies** [comment]
Sorta making some progress https://cirrus-ci.com/github/rasterio/rasterio-wheels/issue75 maybe?

**Comment by snowman2** [comment]
Thanks @sgillies :+1: 

https://github.com/rasterio/rasterio-wheels/pull/99
